config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :messages
  resources :my_scaffolds

end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/my_scaffold.rb
class MyScaffold < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
@message.message_text="Changed the message text"
    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.html { redirect_to @message, notice: 'Changes were made in the controller' }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:user, :message_text)
    end
end

app/controllers/my_scaffolds_controller.rb
class MyScaffoldsController < ApplicationController
  before_action :set_my_scaffold, only: [:show, :edit, :update, :destroy]

  # GET /my_scaffolds
  # GET /my_scaffolds.json
  def index
    @my_scaffolds = MyScaffold.all
  end

  # GET /my_scaffolds/1
  # GET /my_scaffolds/1.json
  def show
  end

  # GET /my_scaffolds/new
  def new
    @my_scaffold = MyScaffold.new
  end

  # GET /my_scaffolds/1/edit
  def edit
  end

  # POST /my_scaffolds
  # POST /my_scaffolds.json
  def create
    @my_scaffold = MyScaffold.new(my_scaffold_params)

    respond_to do |format|
      if @my_scaffold.save
        format.html { redirect_to @my_scaffold, notice: 'My scaffold was successfully created.' }
        format.json { render :show, status: :created, location: @my_scaffold }
      else
        format.html { render :new }
        format.json { render json: @my_scaffold.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_scaffolds/1
  # PATCH/PUT /my_scaffolds/1.json
  def update
    respond_to do |format|
      if @my_scaffold.update(my_scaffold_params)
        format.html { redirect_to @my_scaffold, notice: 'My scaffold was successfully updated.' }
        format.json { render :show, status: :ok, location: @my_scaffold }
      else
        format.html { render :edit }
        format.json { render json: @my_scaffold.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_scaffolds/1
  # DELETE /my_scaffolds/1.json
  def destroy
    @my_scaffold.destroy
    respond_to do |format|
      format.html { redirect_to my_scaffolds_url, notice: 'My scaffold was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_scaffold
      @my_scaffold = MyScaffold.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_scaffold_params
      params.require(:my_scaffold).permit(:my_string, :my_integer, :my_datetime, :my_boolean)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/my_scaffolds_helper.rb
module MyScaffoldsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Angel</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :message_text %><br>
    <%= f.text_area :message_text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Messages</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Message text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.user %></td>
        <td><%= message.message_text %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @message.user %>
</p>

<p>
  <strong>Message text:</strong>
  <%= @message.message_text %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/my_scaffolds/_form.html.erb
<%= form_for(@my_scaffold) do |f| %>
  <% if @my_scaffold.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@my_scaffold.errors.count, "error") %> prohibited this my_scaffold from being saved:</h2>

      <ul>
      <% @my_scaffold.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :my_string %><br>
    <%= f.text_field :my_string %>
  </div>
  <div class="field">
    <%= f.label :my_integer %><br>
    <%= f.number_field :my_integer %>
  </div>
  <div class="field">
    <%= f.label :my_datetime %><br>
    <%= f.datetime_select :my_datetime %>
  </div>
  <div class="field">
    <%= f.label :my_boolean %><br>
    <%= f.check_box :my_boolean %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/my_scaffolds/edit.html.erb
<h1>Editing My Scaffold</h1>

<%= render 'form' %>

<%= link_to 'Show', @my_scaffold %> |
<%= link_to 'Back', my_scaffolds_path %>

app/views/my_scaffolds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing My Scaffolds</h1>

<table>
  <thead>
    <tr>
      <th>My string</th>
      <th>My integer</th>
      <th>My datetime</th>
      <th>My boolean</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_scaffolds.each do |my_scaffold| %>
      <tr>
        <td><%= my_scaffold.my_string %></td>
        <td><%= my_scaffold.my_integer %></td>
        <td><%= my_scaffold.my_datetime %></td>
        <td><%= my_scaffold.my_boolean %></td>
        <td><%= link_to 'Show', my_scaffold %></td>
        <td><%= link_to 'Edit', edit_my_scaffold_path(my_scaffold) %></td>
        <td><%= link_to 'Destroy', my_scaffold, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New My scaffold', new_my_scaffold_path %>

app/views/my_scaffolds/new.html.erb
<h1>New My Scaffold</h1>

<%= render 'form' %>

<%= link_to 'Back', my_scaffolds_path %>

app/views/my_scaffolds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>My string:</strong>
  <%= @my_scaffold.my_string %>
</p>

<p>
  <strong>My integer:</strong>
  <%= @my_scaffold.my_integer %>
</p>

<p>
  <strong>My datetime:</strong>
  <%= @my_scaffold.my_datetime %>
</p>

<p>
  <strong>My boolean:</strong>
  <%= @my_scaffold.my_boolean %>
</p>

<%= link_to 'Edit', edit_my_scaffold_path(@my_scaffold) %> |
<%= link_to 'Back', my_scaffolds_path %>